/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;

public class App {
    public void compute(int[] inputHolder, int[] outputHolder) {
        if (inputHolder[0] > 10) {
            outputHolder[0] = 1;
        }

        if (inputHolder[0] > 5) {
            outputHolder[0] *= 2;
        }
    }

    public static void main(String[] args) {
        int[] sharedData = {12};
        new App().compute(sharedData, sharedData);
        System.out.println(Arrays.toString(sharedData));
    }
}
